#Set give-xp-direct to "true" (without the quotes) for mobs to not drop xp,
#but instead the player gets the xp directly. Default false
give-xp-direct: false

#These values allow you to choose if players get the notifications when they kill
#a mob or break blocks defined in the Blocks.yml file.
block-notifications: true
mob-notifications: true

#This plugin uses metrics. If you do not wish to participate, then set
#opt-out-metrics to true. Please do not opt out, it supports plugin developers.

opt-out-metrics: false

#DO NOT TOUCH THIS NEXT VALUE, OTHERWISE IT WILL ERASE YOUR CONFIG. IT IS USED
#FOR CHECKING UPDATES IN THE CONFIG.
seriously-do-not-change-this: 5